### ISSUE TITLE
Логическая ошибка

### ISSUE THREAD

**Issue by Nervniy1Enot** [nevermorest/THP-CS-Debug#1]
Для количества рук оружия прописано значение от 1 до 2 (integer), но при этом вы принимаете значение 3, что является логической ошибкой. Ведь максимальное количество рук у человека - 2.

**Comment by nevermorest** [comment]
Commit [f978cf1](https://github.com/nevermorest/THP-CS-Debug/commit/f978cf1da0fe6c951c170b202213a35a3ace6741)
